# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Russell Dunphy - parenthesis pusher, painter of cats and dogs.
email: me@rsslldnphy.com
description: > # this means to ignore newlines until "baseurl:"
  Russell Dunphy - parenthesis pusher, painter of cats and dogs. Does the
  occasional other thing too. You can find most of them here.
  "Clojure", "functional programming", "lopsided dog portraits", and
  "giant cats eating the world" are all keywords/phrases I'd like Google's
  ranking algorithm to score me highly for, which is why I've put them in this description.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rsslldnphy.com" # the base hostname & protocol for your site

twitter_username: rsslldnphy
github_username: rsslldnphy
linkedin_username: rsslldnphy
facebook_username: russell.dunphy

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jemoji
